// DPD Pickup pakomātu saraksts Latvijā — statisks, atjaunots 2026
export const DPD_PAKOMATI = [
  // ── Rīga ──
  { id:'dpd-0',   city:'Rīga', name:'DPD Aibe Buļļu',                    address:'Buļļu iela 35, Rīga' },
  { id:'dpd-1',   city:'Rīga', name:'DPD Akropole',                       address:'Latgales iela 257, Rīga' },
  { id:'dpd-2',   city:'Rīga', name:'DPD Alfa',                           address:'Brīvības gatve 372, Rīga' },
  { id:'dpd-3',   city:'Rīga', name:'DPD Artilērijas',                    address:'Artilērijas iela 40, Rīga' },
  { id:'dpd-4',   city:'Rīga', name:'DPD Barona Centrs',                  address:'Krišjāņa Barona iela 46, Rīga' },
  { id:'dpd-5',   city:'Rīga', name:'DPD BETA Purvciems',                 address:'Purvciema iela 35, Rīga' },
  { id:'dpd-6',   city:'Rīga', name:'DPD BETA Rušonu',                    address:'Rušonu iela 17A, Rīga' },
  { id:'dpd-7',   city:'Rīga', name:'DPD Bērnu Pasaule',                  address:'Matīsa iela 25, Rīga' },
  { id:'dpd-8',   city:'Rīga', name:'DPD Brīvības 44',                    address:'Brīvības iela 44, Rīga' },
  { id:'dpd-9',   city:'Rīga', name:'DPD Brīvības 78',                    address:'Brīvības iela 78a, Rīga' },
  { id:'dpd-10',  city:'Rīga', name:'DPD Circle K Botānika',              address:'Jūrmalas gatve 5a, Rīga' },
  { id:'dpd-11',  city:'Rīga', name:'DPD Circle K Brīvības/Cēsu',         address:'Brīvības iela 176a, Rīga' },
  { id:'dpd-12',  city:'Rīga', name:'DPD Circle K Deglava',               address:'Augusta Deglava iela 164a, Rīga' },
  { id:'dpd-13',  city:'Rīga', name:'DPD Circle K Dzelzavas',             address:'Dzelzavas iela 14, Rīga' },
  { id:'dpd-14',  city:'Rīga', name:'DPD Circle K Iļģuciems',             address:'Dzirciema iela 40, Rīga' },
  { id:'dpd-15',  city:'Rīga', name:'DPD Circle K Imanta',                address:'Anniņmuižas bulvāris 25a, Rīga' },
  { id:'dpd-16',  city:'Rīga', name:'DPD Circle K Kurbada',               address:'Kurbada iela 8, Rīga' },
  { id:'dpd-17',  city:'Rīga', name:'DPD Circle K Lubānas',               address:'Lubānas iela 119A, Rīga' },
  { id:'dpd-18',  city:'Rīga', name:'DPD Circle K Muitas',                address:'Muitas iela 4, Rīga' },
  { id:'dpd-19',  city:'Rīga', name:'DPD Circle K Pērnavas',              address:'Pērnavas iela 7, Rīga' },
  { id:'dpd-20',  city:'Rīga', name:'DPD Circle K Teika',                 address:'Brīvības gatve 265, Rīga' },
  { id:'dpd-21',  city:'Rīga', name:'DPD Circle K Valdemāra',             address:'Krišjāna Valdemāra iela 104, Rīga' },
  { id:'dpd-22',  city:'Rīga', name:'DPD Citro Imanta',                   address:'Kurzemes prospekts 160A, Rīga' },
  { id:'dpd-23',  city:'Rīga', name:'DPD Citro Ziepniekkalns',            address:'Ozolciema iela 46 k-6, Rīga' },
  { id:'dpd-24',  city:'Rīga', name:'DPD Čiekurkalns',                    address:'Čiekurkalna 2.līnija 30, Rīga' },
  { id:'dpd-25',  city:'Rīga', name:'DPD Damme',                          address:'Kurzemes prospekts 1a, Rīga' },
  { id:'dpd-26',  city:'Rīga', name:'DPD Dārziņi',                        address:'Taisnā iela 71A, Rīga' },
  { id:'dpd-27',  city:'Rīga', name:'DPD Dole',                           address:'Latgales iela 357, Rīga' },
  { id:'dpd-28',  city:'Rīga', name:'DPD Domina',                         address:'Ieriķu iela 3, Rīga' },
  { id:'dpd-29',  city:'Rīga', name:'DPD Birojs',                         address:'Uriekstes iela 8a, Rīga' },
  { id:'dpd-30',  city:'Rīga', name:'DPD Drogas Jugla',                   address:'Brīvības gatve 432, Rīga' },
  { id:'dpd-31',  city:'Rīga', name:'DPD Elemental Skanste',              address:'Skanstes iela 25, Rīga' },
  { id:'dpd-32',  city:'Rīga', name:'DPD Ēbelmuiža',                      address:'Valdeķu iela 39, Rīga' },
  { id:'dpd-33',  city:'Rīga', name:'DPD Galleria Riga',                  address:'Dzirnavu iela 67, Rīga' },
  { id:'dpd-34',  city:'Rīga', name:'DPD Hipokrāta',                      address:'Hipokrāta iela 26, Rīga' },
  { id:'dpd-35',  city:'Rīga', name:'DPD IXO Centrs',                     address:'Anniņmuižas iela 17, Rīga' },
  { id:'dpd-36',  city:'Rīga', name:'DPD Jaunā Teika',                    address:'Gustava Zemgala gatve 78, Rīga' },
  { id:'dpd-37',  city:'Rīga', name:'DPD Kurši Vienības',                 address:'Vienības gatve 113, Rīga' },
  { id:'dpd-38',  city:'Rīga', name:'DPD LaTS Bolderāja',                 address:'Lemešu iela 20, Rīga' },
  { id:'dpd-39',  city:'Rīga', name:'DPD LaTS Plostu',                    address:'Plostu iela 29, Rīga' },
  { id:'dpd-40',  city:'Rīga', name:'DPD Maxima Burtnieku',               address:'Burtnieku iela 39, Rīga' },
  { id:'dpd-41',  city:'Rīga', name:'DPD Maxima Gaigalas',                address:'Gaigalas iela 29, Rīga' },
  { id:'dpd-42',  city:'Rīga', name:'DPD Maxima Kurzemes',                address:'Kurzemes prospekts 59a, Rīga' },
  { id:'dpd-43',  city:'Rīga', name:'DPD Maxima Lidoņu',                  address:'Lidoņu iela 3, Rīga' },
  { id:'dpd-44',  city:'Rīga', name:'DPD Maxima Rusova',                  address:'Rusova iela 1, Rīga' },
  { id:'dpd-45',  city:'Rīga', name:'DPD Maxima Vecmīlgrāvis',            address:'Augusta Dombrovska iela 74, Rīga' },
  { id:'dpd-46',  city:'Rīga', name:'DPD Maxima Višķu',                   address:'Višķu iela 14, Rīga' },
  { id:'dpd-47',  city:'Rīga', name:'DPD Maxima X Āgenskalns',            address:'Pilsoņu iela 1 k-1, Rīga' },
  { id:'dpd-48',  city:'Rīga', name:'DPD Maxima X Jugla',                 address:'Juglas iela 45, Rīga' },
  { id:'dpd-49',  city:'Rīga', name:'DPD Maxima X Parādes',               address:'Parādes iela 8, Rīga' },
  { id:'dpd-50',  city:'Rīga', name:'DPD Maxima X Ulbrokas',              address:'Ulbrokas iela 4, Rīga' },
  { id:'dpd-51',  city:'Rīga', name:'DPD Maxima Liepājas',                address:'Liepājas iela 76A, Rīga' },
  { id:'dpd-52',  city:'Rīga', name:'DPD Maxima XX Mūkusalas',            address:'Mūkusalas iela 73, Rīga' },
  { id:'dpd-53',  city:'Rīga', name:'DPD Maxima XX Nīcgales',             address:'Nīcgales iela 46a, Rīga' },
  { id:'dpd-54',  city:'Rīga', name:'DPD Maxima XXX Grostonas',           address:'Grostonas iela 1, Rīga' },
  { id:'dpd-55',  city:'Rīga', name:'DPD Maxima XXX Deglava',             address:'A. Deglava iela 67, Rīga' },
  { id:'dpd-56',  city:'Rīga', name:'DPD Mego Biķernieku',                address:'Biķernieku iela 16a, Rīga' },
  { id:'dpd-57',  city:'Rīga', name:'DPD Mego Bolderāja',                 address:'Andreja Saharova iela 20a, Rīga' },
  { id:'dpd-58',  city:'Rīga', name:'DPD Mego Graudu',                    address:'Graudu iela 10, Rīga' },
  { id:'dpd-59',  city:'Rīga', name:'DPD Mego Kleistu',                   address:'Kleistu iela 9, Rīga' },
  { id:'dpd-60',  city:'Rīga', name:'DPD Mego Kurzemes',                  address:'Kurzemes prospekts 132a, Rīga' },
  { id:'dpd-61',  city:'Rīga', name:'DPD Mego Ķengarags',                 address:'Latgales iela 264 k-3, Rīga' },
  { id:'dpd-62',  city:'Rīga', name:'DPD Mego Lidoņu',                    address:'Lidoņu iela 27 k-1, Rīga' },
  { id:'dpd-63',  city:'Rīga', name:'DPD Mego Prūšu',                     address:'Prūšu iela 2, Rīga' },
  { id:'dpd-64',  city:'Rīga', name:'DPD Mego Saharova',                  address:'Andreja Saharova iela 2, Rīga' },
  { id:'dpd-65',  city:'Rīga', name:'DPD Mego Ziepniekkalns',             address:'Dižozolu iela 2, Rīga' },
  { id:'dpd-66',  city:'Rīga', name:'DPD Mēbeļu Nams',                    address:'Dzelzavas iela 72, Rīga' },
  { id:'dpd-67',  city:'Rīga', name:'DPD Miera 2',                        address:'Miera iela 2, Rīga' },
  { id:'dpd-68',  city:'Rīga', name:'DPD Mini Rimi Biķernieku',           address:'Biķernieku iela 21, Rīga' },
  { id:'dpd-69',  city:'Rīga', name:'DPD MIX Deglava',                    address:'Augusta Deglava iela 52, Rīga' },
  { id:'dpd-70',  city:'Rīga', name:'DPD MIX Jasmuižas',                  address:'Jasmuižas iela 9A, Rīga' },
  { id:'dpd-71',  city:'Rīga', name:'DPD Neste Dambja',                   address:'Dambja iela 10, Rīga' },
  { id:'dpd-72',  city:'Rīga', name:'DPD Olimpia',                        address:'Āzenes iela 5, Rīga' },
  { id:'dpd-73',  city:'Rīga', name:'DPD Riga Plaza',                     address:'Mūkusalas iela 71, Rīga' },
  { id:'dpd-74',  city:'Rīga', name:'DPD Rimi Aleja',                     address:'Vienības gatve 194a, Rīga' },
  { id:'dpd-75',  city:'Rīga', name:'DPD Rimi Anniņmuižas',               address:'Anniņmuižas bulvāris 40a, Rīga' },
  { id:'dpd-76',  city:'Rīga', name:'DPD Rimi Āgenskalns',                address:'Mārupes iela 10a, Rīga' },
  { id:'dpd-77',  city:'Rīga', name:'DPD Rimi Biķernieku',                address:'Biķernieku iela 160, Rīga' },
  { id:'dpd-78',  city:'Rīga', name:'DPD Rimi Briāna',                    address:'Krišjāņa Valdemāra iela 62a, Rīga' },
  { id:'dpd-79',  city:'Rīga', name:'DPD Rimi Deglava',                   address:'Augusta Deglava iela 110, Rīga' },
  { id:'dpd-80',  city:'Rīga', name:'DPD Rimi Gramzdas',                  address:'Imantas 15.līnija 7, Rīga' },
  { id:'dpd-81',  city:'Rīga', name:'DPD Rimi Kalnciema',                 address:'Kalnciema iela 41, Rīga' },
  { id:'dpd-82',  city:'Rīga', name:'DPD Rimi Kreimeņu',                  address:'Kreimeņu iela 4a, Rīga' },
  { id:'dpd-83',  city:'Rīga', name:'DPD Rimi Latgales',                  address:'Latgales iela 220B, Rīga' },
  { id:'dpd-84',  city:'Rīga', name:'DPD Rimi Mežaparks',                 address:'Ķīšezera iela 6, Rīga' },
  { id:'dpd-85',  city:'Rīga', name:'DPD Rimi Mini Anniņmuiža',           address:'Anniņmuižas bulvāris 90, Rīga' },
  { id:'dpd-86',  city:'Rīga', name:'DPD Rimi Mini Brīvības',             address:'Brīvības gatve 404, Rīga' },
  { id:'dpd-87',  city:'Rīga', name:'DPD Rimi Mīlgrāvis',                 address:'Mīlgrāvja iela 14, Rīga' },
  { id:'dpd-88',  city:'Rīga', name:'DPD Rimi P. Brieža',                 address:'Pulkveža Brieža iela 33a, Rīga' },
  { id:'dpd-89',  city:'Rīga', name:'DPD Rimi Purvciems',                 address:'Nīcgales iela 2, Rīga' },
  { id:'dpd-90',  city:'Rīga', name:'DPD Rimi Sadovņikova',               address:'Firsa Sadovņikova iela 14, Rīga' },
  { id:'dpd-91',  city:'Rīga', name:'DPD Rimi Saharova',                  address:'Andreja Saharova iela 23a, Rīga' },
  { id:'dpd-92',  city:'Rīga', name:'DPD Rimi Salnas',                    address:'Salanas iela 1a, Rīga' },
  { id:'dpd-93',  city:'Rīga', name:'DPD Rimi Seiles',                    address:'Valērijas Seiles iela 6, Rīga' },
  { id:'dpd-94',  city:'Rīga', name:'DPD Rimi Stirnu',                    address:'Stirnu iela 26, Rīga' },
  { id:'dpd-95',  city:'Rīga', name:'DPD Rimi Dzelzavas',                 address:'Dzelzavas iela 78, Rīga' },
  { id:'dpd-96',  city:'Rīga', name:'DPD Rimi Tilta',                     address:'Tilta iela 32, Rīga' },
  { id:'dpd-97',  city:'Rīga', name:'DPD Rimi Vaidelotes',                address:'Vaidelotes iela 11a, Rīga' },
  { id:'dpd-98',  city:'Rīga', name:'DPD Rimi Valdemārs',                 address:'Krišjāņa Valdemāra iela 112, Rīga' },
  { id:'dpd-99',  city:'Rīga', name:'DPD Rimi Vecmīlgrāvis',              address:'Augusta Dombrovska iela 23, Rīga' },
  { id:'dpd-100', city:'Rīga', name:'DPD Spice',                          address:'Lielirbes iela 29, Rīga' },
  { id:'dpd-101', city:'Rīga', name:'DPD Stabu 24',                       address:'Stabu iela 24, Rīga' },
  { id:'dpd-102', city:'Rīga', name:'DPD Tallinas',                       address:'Tallinas iela 66B, Rīga' },
  { id:'dpd-103', city:'Rīga', name:'DPD TC Gaiļezers',                   address:'Gaiļezera iela 8, Rīga' },
  { id:'dpd-104', city:'Rīga', name:'DPD TC Jugla',                       address:'Juglas krastmala 2, Rīga' },
  { id:'dpd-105', city:'Rīga', name:'DPD TC Mežciems',                    address:'Biķernieku iela 143, Rīga' },
  { id:'dpd-106', city:'Rīga', name:'DPD TC ORIGO',                       address:'Satekles iela 2B, Rīga' },
  { id:'dpd-107', city:'Rīga', name:'DPD TC OZOLS',                       address:'Mazā Rencēnu iela 1, Rīga' },
  { id:'dpd-108', city:'Rīga', name:'DPD TC Venta',                       address:'Zolitūdes iela 34, Rīga' },
  { id:'dpd-109', city:'Rīga', name:'DPD Teika Plaza',                    address:'Brīvības gatve 201, Rīga' },
  { id:'dpd-110', city:'Rīga', name:'DPD Tēriņu 55',                      address:'Tēriņu iela 55, Rīga' },
  { id:'dpd-111', city:'Rīga', name:'DPD TOP Daugavgrīvas',               address:'Daugavgrīvas iela 72, Rīga' },
  { id:'dpd-112', city:'Rīga', name:'DPD TOP Ilūkstes',                   address:'Ilūkstes iela 44A, Rīga' },
  { id:'dpd-113', city:'Rīga', name:'DPD TOP Viestura prospekts',         address:'Viestura prospekts 35A, Rīga' },
  { id:'dpd-114', city:'Rīga', name:'DPD TOP Zalves',                     address:'Zalves iela 46a, Rīga' },
  { id:'dpd-115', city:'Rīga', name:'DPD TOP Zasulauks',                  address:'Vecā Jūrmalas gatve 1, Rīga' },
  { id:'dpd-116', city:'Rīga', name:'DPD TOP Ziepniekkalns',              address:'Ozolciema iela 16 K-4, Rīga' },
  { id:'dpd-117', city:'Rīga', name:'DPD Verde',                          address:'Roberta Hirša iela 1, Rīga' },
  { id:'dpd-118', city:'Rīga', name:'DPD VIRŠI Arkādijs',                 address:'Uzvaras bulvāris 16, Rīga' },
  { id:'dpd-119', city:'Rīga', name:'DPD VIRŠI Katrīnas dambis',          address:'Katrīnas dambis 35, Rīga' },
  { id:'dpd-120', city:'Rīga', name:'DPD VIRŠI Pērnava',                  address:'Pērnavas iela 78, Rīga' },
  { id:'dpd-121', city:'Rīga', name:'DPD Ziedu Bāze Kapseļu',            address:'Kapseļu iela 15, Rīga' },
  { id:'dpd-122', city:'Rīga', name:'DPD Zoom',                           address:'Latgales iela 400, Rīga' },
  // ── Ārpus Rīgas ──
  { id:'dpd-123', city:'Aglona',       name:'DPD VIRŠI Aglona',           address:'Somersētas iela 11a, Aglona' },
  { id:'dpd-124', city:'Ainaži',       name:'DPD Ainaži',                 address:'Valdemāra iela 36, Ainaži' },
  { id:'dpd-125', city:'Aizkraukle',   name:'DPD Maxima X Aizkraukle',    address:'Gaismas iela 22, Aizkraukle' },
  { id:'dpd-126', city:'Aizkraukle',   name:'DPD TOP Aizkraukle',         address:'Lāčplēša iela 7, Aizkraukle' },
  { id:'dpd-127', city:'Aizpute',      name:'DPD TC Aizpute',             address:'Zvaigzņu iela 2, Aizpute' },
  { id:'dpd-128', city:'Aknīste',      name:'DPD TOP Aknīste',            address:'Dzirnavu iela 1, Aknīste' },
  { id:'dpd-129', city:'Alsunga',      name:'DPD Citro Alsunga',          address:'Skolas iela 5, Alsunga' },
  { id:'dpd-130', city:'Alūksne',      name:'DPD Maxima X Alūksne',       address:'Pils iela 9a, Alūksne' },
  { id:'dpd-131', city:'Alūksne',      name:'DPD Mājai & Dārzam Alūksne', address:'Latgales iela 3B, Alūksne' },
  { id:'dpd-132', city:'Alūksne',      name:'DPD LaTS Alūksne',           address:'Torņa iela 2A, Alūksne' },
  { id:'dpd-133', city:'Ape',          name:'DPD TOP Ape',                address:'Stacijas iela 4, Ape' },
  { id:'dpd-134', city:'Auce',         name:'DPD Raiņa 5 Auce',           address:'Raiņa iela 5, Auce' },
  { id:'dpd-135', city:'Augšlīgatne',  name:'DPD Elvi Augšlīgatne',       address:'Nītaures iela 5, Augšlīgatne' },
  { id:'dpd-136', city:'Ādaži',        name:'DPD TC Apelsīns Ādaži',      address:'Rīgas gatve 5, Ādaži' },
  { id:'dpd-137', city:'Ādaži',        name:'DPD Rimi Mini Ādaži',        address:'Gaujas iela 6, Ādaži' },
  { id:'dpd-138', city:'Ādaži',        name:'DPD VIRŠI Ādaži',            address:'Rīgas gatve 45, Ādaži' },
  { id:'dpd-139', city:'Ādaži',        name:'DPD TOP Ādaži',              address:'Gaujas iela 20, Ādaži' },
  { id:'dpd-140', city:'Babīte',       name:'DPD Elvi Babīte',            address:'Liepu aleja 15a, Babīte' },
  { id:'dpd-141', city:'Baldone',      name:'DPD Elvi Baldone',           address:'Pilskalna iela 3, Baldone' },
  { id:'dpd-142', city:'Baldone',      name:'DPD Mego Baldone',           address:'Rīgas iela 79K-1, Baldone' },
  { id:'dpd-143', city:'Baloži',       name:'DPD Maxima Baloži',          address:'Baložu iela 5, Baloži' },
  { id:'dpd-144', city:'Baloži',       name:'DPD Mego Baloži',            address:'Rīgas iela 14, Baloži' },
  { id:'dpd-145', city:'Baltinava',    name:'DPD Lats Baltinava',         address:'Kārsavas iela 4, Baltinava' },
  { id:'dpd-146', city:'Balvi',        name:'DPD TC Planēta Balvi',       address:'Brīvības iela 57, Balvi' },
  { id:'dpd-147', city:'Balvi',        name:'DPD TOP Balvi',              address:'Partizānu iela 6, Balvi' },
  { id:'dpd-148', city:'Bauska',       name:'DPD Mājai & Dārzam Bauska',  address:'Salātu iela 24, Bauska' },
  { id:'dpd-149', city:'Bauska',       name:'DPD Rimi Bauska',            address:'Pionieru iela 2, Bauska' },
  { id:'dpd-150', city:'Bauska',       name:'DPD Rimi Mini Bauska',       address:'Zaļā iela 3, Bauska' },
  { id:'dpd-151', city:'Brocēni',      name:'DPD Citro Brocēni',          address:'Lielcieceres iela 2a, Brocēni' },
  { id:'dpd-152', city:'Bukulti',      name:'DPD SPAR Bukulti',           address:'Ādažu iela 26A, Bukulti' },
  { id:'dpd-153', city:'Carnikava',    name:'DPD Mego Carnikava',         address:'Rīgas iela 14A, Carnikava' },
  { id:'dpd-154', city:'Carnikava',    name:'DPD Vesko Carnikava',        address:'Tulpju iela 1A, Carnikava' },
  { id:'dpd-155', city:'Cesvaine',     name:'DPD LaTS Cesvaine',          address:'Rīgas iela 2, Cesvaine' },
  { id:'dpd-156', city:'Cēsis',        name:'DPD Maxima XX Cēsis',        address:'Valmieras iela 17A, Cēsis' },
  { id:'dpd-157', city:'Cēsis',        name:'DPD SOLO Cēsis',             address:'Jāņa Poruka iela 19, Cēsis' },
  { id:'dpd-158', city:'Cēsis',        name:'DPD TC Globuss Cēsis',       address:'Raiņa iela 26/28, Cēsis' },
  { id:'dpd-159', city:'Cēsis',        name:'DPD TOP Cēsis',              address:'Gaujas iela 29, Cēsis' },
  { id:'dpd-160', city:'Dagda',        name:'DPD TOP Dagda',              address:'Daugavpils iela 6, Dagda' },
  { id:'dpd-161', city:'Daugavpils',   name:'DPD Aveņu Centrs Daugavpils',address:'Raipoles iela 11, Daugavpils' },
  { id:'dpd-162', city:'Daugavpils',   name:'DPD Circle K Daugavpils',    address:'Ventspils iela 28, Daugavpils' },
  { id:'dpd-163', city:'Daugavpils',   name:'DPD Autoosta Daugavpils',    address:'Viestura iela 10, Daugavpils' },
  { id:'dpd-164', city:'Daugavpils',   name:'DPD TC Ditton Daugavpils',   address:'Cietokšņa iela 60, Daugavpils' },
  { id:'dpd-165', city:'Daugavpils',   name:'DPD Labais Daugavpils',      address:'Lielā iela 44, Daugavpils' },
  { id:'dpd-166', city:'Daugavpils',   name:'DPD Maxima Piekrastes Daugavpils', address:'Piekrastes iela 29, Daugavpils' },
  { id:'dpd-167', city:'Daugavpils',   name:'DPD Maxima X Smilšu Daugavpils', address:'Smilšu iela 98, Daugavpils' },
  { id:'dpd-168', city:'Dobele',       name:'DPD Mājai & Dārzam Dobele',  address:'Bauskas iela 4, Dobele' },
  { id:'dpd-169', city:'Dobele',       name:'DPD Rimi Dobele',            address:'Brīvības iela 30, Dobele' },
  { id:'dpd-170', city:'Dobele',       name:'DPD TOP Dobele',             address:'Muldavas iela 3A, Dobele' },
  { id:'dpd-171', city:'Dundaga',      name:'DPD Dundaga',                address:'Talsu iela 1, Dundaga' },
  { id:'dpd-172', city:'Engure',       name:'DPD Engure',                 address:'Jūras iela 81, Engure' },
  { id:'dpd-173', city:'Ērgļi',        name:'DPD TOP Ērgļi',              address:'Zaļā iela 1, Ērgļi' },
  { id:'dpd-174', city:'Garkalne',     name:'DPD Lats Garkalne',          address:'Vidzemes šoseja 13, Garkalne' },
  { id:'dpd-175', city:'Grobiņa',      name:'DPD TOP Grobiņa',            address:'Lielā iela 74, Grobiņa' },
  { id:'dpd-176', city:'Gulbene',      name:'DPD Dzelzceļa Gulbene',      address:'Dzelzceļa iela 14, Gulbene' },
  { id:'dpd-177', city:'Gulbene',      name:'DPD TOP Gulbene',            address:'Nākotnes iela 6, Gulbene' },
  { id:'dpd-178', city:'Iecava',       name:'DPD Maxima Iecava',          address:'Rīgas iela 27, Iecava' },
  { id:'dpd-179', city:'Iecava',       name:'DPD TOP Iecava',             address:'Edvarta Virzas iela 2, Iecava' },
  { id:'dpd-180', city:'Ikšķile',      name:'DPD Elvi Ikšķile',           address:'Daugavas prospekts 18A, Ikšķile' },
  { id:'dpd-181', city:'Ikšķile',      name:'DPD Rimi Ikšķile',           address:'Melioratoru iela 1A, Ikšķile' },
  { id:'dpd-182', city:'Ilūkste',      name:'DPD TOP Ilūkste',            address:'Pilskalnes iela 2A, Ilūkste' },
  { id:'dpd-183', city:'Inčukalns',    name:'DPD Inčukalns',              address:'Atmodas iela 6, Inčukalns' },
  { id:'dpd-184', city:'Jaunjelgava',  name:'DPD Jaunjelgava',            address:'Jelgavas iela 44, Jaunjelgava' },
  { id:'dpd-185', city:'Jaunmārupe',   name:'DPD Jaunmārupe',             address:'Mazcenu aleja 33/1, Jaunmārupe' },
  { id:'dpd-186', city:'Jaunolaine',   name:'DPD Jaunolaine',             address:'Baznīcas iela 10, Jaunolaine' },
  { id:'dpd-187', city:'Jaunpiebalga', name:'DPD Jaunpiebalga',           address:'Gaujas iela 4, Jaunpiebalga' },
  { id:'dpd-188', city:'Jelgava',      name:'DPD Birzes Jelgava',         address:'Birzes iela 21, Jelgava' },
  { id:'dpd-189', city:'Jelgava',      name:'DPD Lielā ELVI Jelgava',     address:'Lielā iela 49, Jelgava' },
  { id:'dpd-190', city:'Jelgava',      name:'DPD RAF Centrs Jelgava',     address:'Rīgas iela 48, Jelgava' },
  { id:'dpd-191', city:'Jelgava',      name:'DPD Rimi Jelgava',           address:'Satiksmes iela 35, Jelgava' },
  { id:'dpd-192', city:'Jelgava',      name:'DPD TC Vivo Jelgava',        address:'Katoļu iela 18, Jelgava' },
  { id:'dpd-193', city:'Jelgava',      name:'DPD Vienības Jelgava',       address:'Vienības iela 2, Jelgava' },
  { id:'dpd-194', city:'Jēkabpils',    name:'DPD Nameja ielas TOP Jēkabpils', address:'Nameja iela 12, Jēkabpils' },
  { id:'dpd-195', city:'Jēkabpils',    name:'DPD Rimi Jēkabpils',         address:'Rīgas iela 120, Jēkabpils' },
  { id:'dpd-196', city:'Jēkabpils',    name:'DPD TC Sēlija Jēkabpils',    address:'Vienības iela 7, Jēkabpils' },
  { id:'dpd-197', city:'Jēkabpils',    name:'DPD TC Sprīdītis Jēkabpils', address:'Celtnieku iela 1, Jēkabpils' },
  { id:'dpd-198', city:'Jūrmala',      name:'DPD Jūrmala Kauguri',        address:'Talsu šoseja 29, Jūrmala' },
  { id:'dpd-199', city:'Jūrmala',      name:'DPD Jūrmala Liedags',        address:'Ventspils šoseja 32, Jūrmala' },
  { id:'dpd-200', city:'Jūrmala',      name:'DPD Jūrmala Rimi Dubulti',   address:'Strēlnieku prospekts 5, Jūrmala' },
  { id:'dpd-201', city:'Kandava',      name:'DPD Kandava',                address:'Lielā iela 1, Kandava' },
  { id:'dpd-202', city:'Kalnciems',    name:'DPD Kalnciems',              address:'Lielā iela 11, Kalnciems' },
  { id:'dpd-203', city:'Kārsava',      name:'DPD Kārsava',                address:'Sporta iela 6, Kārsava' },
  { id:'dpd-204', city:'Koknese',      name:'DPD Koknese',                address:'Hanzas iela 1, Koknese' },
  { id:'dpd-205', city:'Krāslava',     name:'DPD Krāslava',               address:'Rīgas iela 28, Krāslava' },
  { id:'dpd-206', city:'Kuldīga',      name:'DPD Rimi Kuldīga',           address:'Sūru iela 2, Kuldīga' },
  { id:'dpd-207', city:'Kuldīga',      name:'DPD ELVI Kuldīga',           address:'Gravas iela 1, Kuldīga' },
  { id:'dpd-208', city:'Ķekava',       name:'DPD Ķekava',                 address:'Nākotnes iela 1, Ķekava' },
  { id:'dpd-209', city:'Ķekava',       name:'DPD Rimi Ķekava',            address:'Rīgas iela 22, Ķekava' },
  { id:'dpd-210', city:'Lielvārde',    name:'DPD Lielvārde',              address:'Lāčplēša iela 16, Lielvārde' },
  { id:'dpd-211', city:'Liepāja',      name:'DPD ELVI Liepāja',           address:'Ganību iela 69/71, Liepāja' },
  { id:'dpd-212', city:'Liepāja',      name:'DPD Kuršu laukums Liepāja',  address:'Kuršu laukums 10, Liepāja' },
  { id:'dpd-213', city:'Liepāja',      name:'DPD Rimi Liepāja',           address:'Ziemeļu iela 13, Liepāja' },
  { id:'dpd-214', city:'Liepāja',      name:'DPD TC Baata Liepāja',       address:'Klaipēdas iela 104C, Liepāja' },
  { id:'dpd-215', city:'Liepāja',      name:'DPD TC Rietumu centrs Liepāja', address:'Jaunā Ostmala 3/5, Liepāja' },
  { id:'dpd-216', city:'Limbaži',      name:'DPD Limbaži',                address:'Cēsu iela 23, Limbaži' },
  { id:'dpd-217', city:'Līvāni',       name:'DPD Līvāni',                 address:'Rīgas iela 89, Līvāni' },
  { id:'dpd-218', city:'Ludza',        name:'DPD Ludza',                  address:'Stacijas iela 30, Ludza' },
  { id:'dpd-219', city:'Madona',       name:'DPD Madona',                 address:'Rūpniecības iela 47, Madona' },
  { id:'dpd-220', city:'Madona',       name:'DPD TOP Madona',             address:'Raiņa iela 34, Madona' },
  { id:'dpd-221', city:'Malta',        name:'DPD Malta',                  address:'1. maija iela 44, Malta' },
  { id:'dpd-222', city:'Mazsalaca',    name:'DPD Mazsalaca',              address:'Parka iela 1, Mazsalaca' },
  { id:'dpd-223', city:'Mārupe',       name:'DPD Mārupe',                 address:'Daugavas iela 36, Mārupe' },
  { id:'dpd-224', city:'Mārupe',       name:'DPD Rimi Mārupe',            address:'Daugavas iela 31, Mārupe' },
  { id:'dpd-225', city:'Mērsrags',     name:'DPD Mērsrags',               address:'Lielā iela 31, Mērsrags' },
  { id:'dpd-226', city:'Nereta',       name:'DPD Nereta',                 address:'Raiņa iela 6, Nereta' },
  { id:'dpd-227', city:'Ogre',         name:'DPD Ogre',                   address:'Brīvības iela 19, Ogre' },
  { id:'dpd-228', city:'Ogre',         name:'DPD Rimi Ogre',              address:'Rīgas iela 33, Ogre' },
  { id:'dpd-229', city:'Ogre',         name:'DPD TC Dauga Ogre',          address:'Rīgas iela 23, Ogre' },
  { id:'dpd-230', city:'Olaine',       name:'DPD Olaine',                 address:'Zemgales iela 24, Olaine' },
  { id:'dpd-231', city:'Ozolnieki',    name:'DPD Ozolnieki',              address:'Rīgas iela 42, Ozolnieki' },
  { id:'dpd-232', city:'Pāvilosta',    name:'DPD Pāvilosta',              address:'Dzintaru iela 69, Pāvilosta' },
  { id:'dpd-233', city:'Piņķi',        name:'DPD Piņķi',                  address:'Rīgas iela 23, Piņķi' },
  { id:'dpd-234', city:'Pļaviņas',     name:'DPD Pļaviņas',               address:'Daugavas iela 85, Pļaviņas' },
  { id:'dpd-235', city:'Preiļi',       name:'DPD Preiļi',                 address:'Brīvības iela 4, Preiļi' },
  { id:'dpd-236', city:'Priekule',     name:'DPD Priekule',               address:'Galvenā iela 1, Priekule' },
  { id:'dpd-237', city:'Priekuļi',     name:'DPD Priekuļi',               address:'Cēsu prospekts 44, Priekuļi' },
  { id:'dpd-238', city:'Rauna',        name:'DPD Rauna',                  address:'Cēsu iela 2A, Rauna' },
  { id:'dpd-239', city:'Rēzekne',      name:'DPD Rēzekne Dārzu',          address:'Dārzu iela 63, Rēzekne' },
  { id:'dpd-240', city:'Rēzekne',      name:'DPD Rēzekne Galdnieku RIMI', address:'Galdnieku iela 8, Rēzekne' },
  { id:'dpd-241', city:'Rēzekne',      name:'DPD Rēzekne Atbrīvošanas',   address:'Atbrīvošanas aleja 141, Rēzekne' },
  { id:'dpd-242', city:'Rēzekne',      name:'DPD Rēzekne Stacijas',       address:'Stacijas iela 20A, Rēzekne' },
  { id:'dpd-243', city:'Roja',         name:'DPD Roja',                   address:'Selgas iela 2, Roja' },
  { id:'dpd-244', city:'Ropaži',       name:'DPD Ropaži',                 address:'Rīgas iela 12, Ropaži' },
  { id:'dpd-245', city:'Rūjiena',      name:'DPD Rūjiena',                address:'Brīvības iela 8, Rūjiena' },
  { id:'dpd-246', city:'Salacgrīva',   name:'DPD Salacgrīva',             address:'Vidzemes iela 3a, Salacgrīva' },
  { id:'dpd-247', city:'Salaspils',    name:'DPD Salaspils',              address:'Skolas iela 4, Salaspils' },
  { id:'dpd-248', city:'Salaspils',    name:'DPD Rimi Salaspils',         address:'Miera iela 24, Salaspils' },
  { id:'dpd-249', city:'Saldus',       name:'DPD Saldus Brīvības',        address:'Brīvības iela 30, Saldus' },
  { id:'dpd-250', city:'Saldus',       name:'DPD Saldus Lielā',           address:'Lielā iela 73, Saldus' },
  { id:'dpd-251', city:'Saulkrasti',   name:'DPD Saulkrasti',             address:'Rīgas iela 51, Saulkrasti' },
  { id:'dpd-252', city:'Sigulda',      name:'DPD Sigulda Gāles Nams',     address:'Gāles iela 23A, Sigulda' },
  { id:'dpd-253', city:'Sigulda',      name:'DPD Sigulda Maxima',         address:'Leona Paegles iela 3, Sigulda' },
  { id:'dpd-254', city:'Sigulda',      name:'DPD Sigulda Šokolāde',       address:'Strēlnieku iela 2, Sigulda' },
  { id:'dpd-255', city:'Skrīveri',     name:'DPD Skrīveri',               address:'Daugavas iela 97, Skrīveri' },
  { id:'dpd-256', city:'Skrunda',      name:'DPD Skrunda',                address:'Ventas iela 13, Skrunda' },
  { id:'dpd-257', city:'Smiltene',     name:'DPD Smiltene Daugavas',      address:'Daugavas iela 1B, Smiltene' },
  { id:'dpd-258', city:'Smiltene',     name:'DPD Smiltene Rīgas',         address:'Rīgas iela 5, Smiltene' },
  { id:'dpd-259', city:'Smiltene',     name:'DPD Smiltene TC Centrs',     address:'Baznīcas laukums 2, Smiltene' },
  { id:'dpd-260', city:'Stende',       name:'DPD Stende',                 address:'Brīvības iela 12, Stende' },
  { id:'dpd-261', city:'Strenči',      name:'DPD Strenči',                address:'Valkas iela 2, Strenči' },
  { id:'dpd-262', city:'Talsi',        name:'DPD Talsi Citro',            address:'Dundagas iela 21, Talsi' },
  { id:'dpd-263', city:'Talsi',        name:'DPD Talsi Rimi',             address:'Dundagas iela 18, Talsi' },
  { id:'dpd-264', city:'Talsi',        name:'DPD Talsi Maxima',           address:'Rīgas iela 8, Talsi' },
  { id:'dpd-265', city:'Tukums',       name:'DPD Tukums Maxima',          address:'Kurzemes iela 36, Tukums' },
  { id:'dpd-266', city:'Tukums',       name:'DPD Tukums Rimi',            address:'Pasta iela 14, Tukums' },
  { id:'dpd-267', city:'Tukums',       name:'DPD Tukums TC Aplis',        address:'Eksporta iela 6, Tukums' },
  { id:'dpd-268', city:'Ulbroka',      name:'DPD Ulbroka',                address:'Institūta iela 7, Ulbroka' },
  { id:'dpd-269', city:'Valka',        name:'DPD Valka Maxima',           address:'Raiņa iela 7, Valka' },
  { id:'dpd-270', city:'Valka',        name:'DPD Valka TC Walk',          address:'Ausekļa iela 54, Valka' },
  { id:'dpd-271', city:'Valmiera',     name:'DPD Valmiera Fabrikas',      address:'Fabrikas iela 2, Valmiera' },
  { id:'dpd-272', city:'Valmiera',     name:'DPD Valmiera Maxima',        address:'Nākotnes iela 2A, Valmiera' },
  { id:'dpd-273', city:'Valmiera',     name:'DPD Valmiera Miera',         address:'Miera iela 5, Valmiera' },
  { id:'dpd-274', city:'Valmiera',     name:'DPD Valmiera Rīgas',         address:'Rīgas iela 64, Valmiera' },
  { id:'dpd-275', city:'Valmiera',     name:'DPD Valmiera Rubenes RIMI',  address:'Rubenes iela 51, Valmiera' },
  { id:'dpd-276', city:'Valmiera',     name:'DPD Valmiera TC Valleta',    address:'Rīgas iela 4, Valmiera' },
  { id:'dpd-277', city:'Vangaži',      name:'DPD Vangaži',                address:'Gaujas iela 19A, Vangaži' },
  { id:'dpd-278', city:'Varakļāni',    name:'DPD Varakļāni',              address:'Pils iela 7D, Varakļāni' },
  { id:'dpd-279', city:'Vecpiebalga',  name:'DPD Vecpiebalga',            address:'Alauksta iela 2, Vecpiebalga' },
  { id:'dpd-280', city:'Vecumnieki',   name:'DPD Vecumnieki',             address:'Rīgas iela 24B, Vecumnieki' },
  { id:'dpd-281', city:'Ventspils',    name:'DPD Ventspils ELVI',         address:'Celtnieku iela 3, Ventspils' },
  { id:'dpd-282', city:'Ventspils',    name:'DPD Ventspils Mego',         address:'Ganību iela 22/24, Ventspils' },
  { id:'dpd-283', city:'Ventspils',    name:'DPD Ventspils Rimi',         address:'J. Poruka iela 5, Ventspils' },
  { id:'dpd-284', city:'Ventspils',    name:'DPD Ventspils TC Tobago',    address:'Lielais prospekts 3/5, Ventspils' },
  { id:'dpd-285', city:'Viesīte',      name:'DPD Viesīte',                address:'Raiņa iela 23, Viesīte' },
  { id:'dpd-286', city:'Viļaka',       name:'DPD Viļaka',                 address:'Balvu iela 5, Viļaka' },
  { id:'dpd-287', city:'Viļāni',       name:'DPD Viļāni',                 address:'Brīvības iela 13, Viļāni' },
  { id:'dpd-288', city:'Zilupe',       name:'DPD Zilupe',                 address:'Brīvības iela 34, Zilupe' },
]
