// Latvijas Pasta pakomātu saraksts — statisks, atjaunots 2026
export const LP_PAKOMATI = [
  // ── Rīga ──
  { id:'lp-0',  city:'Rīga',        name:'LP Pasta centrs Rīga',           address:'Stacijas laukums 1, Rīga' },
  { id:'lp-1',  city:'Rīga',        name:'LP Rīga Brīvības 32',            address:'Brīvības iela 32, Rīga' },
  { id:'lp-2',  city:'Rīga',        name:'LP Rīga Barona 31',              address:'Krišjāņa Barona iela 31, Rīga' },
  { id:'lp-3',  city:'Rīga',        name:'LP Rīga Čaka 57',                address:'Čaka iela 57, Rīga' },
  { id:'lp-4',  city:'Rīga',        name:'LP Rīga Dzirnavu 89',            address:'Dzirnavu iela 89, Rīga' },
  { id:'lp-5',  city:'Rīga',        name:'LP Rīga Ganību dambis 1',        address:'Ganību dambis 1, Rīga' },
  { id:'lp-6',  city:'Rīga',        name:'LP Rīga Imantas 7.līnija',       address:'Imantas 7.līnija 1, Rīga' },
  { id:'lp-7',  city:'Rīga',        name:'LP Rīga Juglas 56',              address:'Juglas iela 56, Rīga' },
  { id:'lp-8',  city:'Rīga',        name:'LP Rīga Kalpaka bulvāris',       address:'Kalpaka bulvāris 2, Rīga' },
  { id:'lp-9',  city:'Rīga',        name:'LP Rīga Kurzemes prospekts 83',  address:'Kurzemes prospekts 83, Rīga' },
  { id:'lp-10', city:'Rīga',        name:'LP Rīga Lāčplēša 45',           address:'Lāčplēša iela 45, Rīga' },
  { id:'lp-11', city:'Rīga',        name:'LP Rīga Marijas 2',              address:'Marijas iela 2, Rīga' },
  { id:'lp-12', city:'Rīga',        name:'LP Rīga Matīsa 61',              address:'Matīsa iela 61, Rīga' },
  { id:'lp-13', city:'Rīga',        name:'LP Rīga Merķeļa 13',            address:'Merķeļa iela 13, Rīga' },
  { id:'lp-14', city:'Rīga',        name:'LP Rīga Miera 48',               address:'Miera iela 48, Rīga' },
  { id:'lp-15', city:'Rīga',        name:'LP Rīga Nīcgales 4',             address:'Nīcgales iela 4, Rīga' },
  { id:'lp-16', city:'Rīga',        name:'LP Rīga Purvciema 5',            address:'Purvciema iela 5, Rīga' },
  { id:'lp-17', city:'Rīga',        name:'LP Rīga Raiņa bulvāris',         address:'Raiņa bulvāris 1, Rīga' },
  { id:'lp-18', city:'Rīga',        name:'LP Rīga Saharova 14',            address:'Andreja Saharova iela 14, Rīga' },
  { id:'lp-19', city:'Rīga',        name:'LP Rīga Slokas 6',               address:'Slokas iela 6, Rīga' },
  { id:'lp-20', city:'Rīga',        name:'LP Rīga Stacijas laukums',       address:'Stacijas laukums 2, Rīga' },
  { id:'lp-21', city:'Rīga',        name:'LP Rīga Tallinas 36',            address:'Tallinas iela 36, Rīga' },
  { id:'lp-22', city:'Rīga',        name:'LP Rīga Valdemāra 77',           address:'Krišjāņa Valdemāra iela 77, Rīga' },
  { id:'lp-23', city:'Rīga',        name:'LP Rīga Vecpilsēta',             address:'Kalēju iela 12, Rīga' },
  { id:'lp-24', city:'Rīga',        name:'LP Rīga Vienības 109',           address:'Vienības gatve 109, Rīga' },
  { id:'lp-25', city:'Rīga',        name:'LP Rīga Ziepniekkalns',          address:'Zemgales prospekts 50, Rīga' },
  { id:'lp-26', city:'Rīga',        name:'LP Rīga Pērsijas 2',             address:'Pērsijas iela 2, Rīga' },
  { id:'lp-27', city:'Rīga',        name:'LP Rīga Mežaparks',              address:'Kokneses prospekts 10, Rīga' },
  { id:'lp-28', city:'Rīga',        name:'LP Rīga Bolderāja',              address:'Daugavgrīvas iela 83, Rīga' },
  { id:'lp-29', city:'Rīga',        name:'LP Rīga Ķengarags',              address:'Maskavas iela 257, Rīga' },
  // ── Rīgas apkārtne ──
  { id:'lp-30', city:'Ādaži',       name:'LP Ādaži',                       address:'Gaujas iela 33, Ādaži' },
  { id:'lp-31', city:'Salaspils',   name:'LP Salaspils',                   address:'Rīgas iela 1, Salaspils' },
  { id:'lp-32', city:'Olaine',      name:'LP Olaine',                      address:'Zemgales iela 33, Olaine' },
  { id:'lp-33', city:'Jūrmala',     name:'LP Jūrmala Majori',              address:'Jomas iela 76, Jūrmala' },
  { id:'lp-34', city:'Jūrmala',     name:'LP Jūrmala Ķemeri',              address:'Tukuma iela 5, Jūrmala' },
  { id:'lp-35', city:'Jūrmala',     name:'LP Jūrmala Sloka',               address:'Dubultu prospekts 2, Jūrmala' },
  { id:'lp-36', city:'Mārupe',      name:'LP Mārupe',                      address:'Skolas iela 4, Mārupe' },
  { id:'lp-37', city:'Ķekava',      name:'LP Ķekava',                      address:'Gaismas iela 19, Ķekava' },
  { id:'lp-38', city:'Carnikava',   name:'LP Carnikava',                   address:'Stacijas iela 5, Carnikava' },
  { id:'lp-39', city:'Saulkrasti',  name:'LP Saulkrasti',                  address:'Ainažu iela 7, Saulkrasti' },
  { id:'lp-40', city:'Vangaži',     name:'LP Vangaži',                     address:'Gaujas iela 11, Vangaži' },
  // ── Vidzeme ──
  { id:'lp-41', city:'Valmiera',    name:'LP Valmiera 1',                  address:'Rīgas iela 34, Valmiera' },
  { id:'lp-42', city:'Valmiera',    name:'LP Valmiera 4 Valleta',          address:'Rīgas iela 4, Valmiera' },
  { id:'lp-43', city:'Cēsis',       name:'LP Cēsis 1',                     address:'Raunas iela 7, Cēsis' },
  { id:'lp-44', city:'Cēsis',       name:'LP Cēsis 2',                     address:'Stacijas iela 5, Cēsis' },
  { id:'lp-45', city:'Sigulda',     name:'LP Sigulda',                     address:'Pils iela 16, Sigulda' },
  { id:'lp-46', city:'Ogre',        name:'LP Ogre',                        address:'Brīvības iela 15, Ogre' },
  { id:'lp-47', city:'Madona',      name:'LP Madona',                      address:'Saieta laukums 1, Madona' },
  { id:'lp-48', city:'Alūksne',     name:'LP Alūksne',                     address:'Pils iela 74, Alūksne' },
  { id:'lp-49', city:'Gulbene',     name:'LP Gulbene',                     address:'Ābeļu iela 2, Gulbene' },
  { id:'lp-50', city:'Mazsalaca',   name:'LP Mazsalaca',                   address:'Baznīcas iela 9, Mazsalaca' },
  { id:'lp-51', city:'Smiltene',    name:'LP Smiltene',                    address:'Dārza iela 3, Smiltene' },
  { id:'lp-52', city:'Limbaži',     name:'LP Limbaži',                     address:'Rīgas iela 16, Limbaži' },
  { id:'lp-53', city:'Salacgrīva',  name:'LP Salacgrīva',                  address:'Rīgas iela 7, Salacgrīva' },
  { id:'lp-54', city:'Ainaži',      name:'LP Ainaži',                      address:'Valdemāra iela 9, Ainaži' },
  { id:'lp-55', city:'Strenči',     name:'LP Strenči',                     address:'Rūjienas iela 12, Strenči' },
  // ── Latgale ──
  { id:'lp-56', city:'Daugavpils',  name:'LP Daugavpils 1',                address:'Saules iela 2, Daugavpils' },
  { id:'lp-57', city:'Daugavpils',  name:'LP Daugavpils 2',                address:'18. novembra iela 14, Daugavpils' },
  { id:'lp-58', city:'Daugavpils',  name:'LP Daugavpils 3',                address:'Rīgas iela 22, Daugavpils' },
  { id:'lp-59', city:'Rēzekne',     name:'LP Rēzekne 1',                   address:'Atbrīvošanas aleja 93, Rēzekne' },
  { id:'lp-60', city:'Rēzekne',     name:'LP Rēzekne 2',                   address:'Baznīcas iela 8, Rēzekne' },
  { id:'lp-61', city:'Preiļi',      name:'LP Preiļi',                      address:'Raiņa bulvāris 19, Preiļi' },
  { id:'lp-62', city:'Krāslava',    name:'LP Krāslava',                    address:'Rīgas iela 22, Krāslava' },
  { id:'lp-63', city:'Ludza',       name:'LP Ludza',                       address:'Stacijas iela 15, Ludza' },
  { id:'lp-64', city:'Balvi',       name:'LP Balvi',                       address:'Brīvības iela 47, Balvi' },
  { id:'lp-65', city:'Viļāni',      name:'LP Viļāni',                      address:'Brīvības iela 8, Viļāni' },
  { id:'lp-66', city:'Līvāni',      name:'LP Līvāni',                      address:'Rīgas iela 4, Līvāni' },
  // ── Zemgale ──
  { id:'lp-67', city:'Jelgava',     name:'LP Jelgava 1',                   address:'Katoļu iela 2B, Jelgava' },
  { id:'lp-68', city:'Jelgava',     name:'LP Jelgava 2',                   address:'Garozas iela 22, Jelgava' },
  { id:'lp-69', city:'Jēkabpils',   name:'LP Jēkabpils 1',                 address:'Brīvības iela 185, Jēkabpils' },
  { id:'lp-70', city:'Bauska',      name:'LP Bauska',                      address:'Slimnīcas iela 1, Bauska' },
  { id:'lp-71', city:'Dobele',      name:'LP Dobele',                      address:'Brīvības iela 30, Dobele' },
  { id:'lp-72', city:'Aizkraukle',  name:'LP Aizkraukle',                  address:'Lāčplēša iela 1A, Aizkraukle' },
  // ── Kurzeme ──
  { id:'lp-73', city:'Liepāja',     name:'LP Liepāja 1',                   address:'Rožu laukums 5, Liepāja' },
  { id:'lp-74', city:'Liepāja',     name:'LP Liepāja 2',                   address:'Grīzupes iela 6, Liepāja' },
  { id:'lp-75', city:'Ventspils',   name:'LP Ventspils 1',                 address:'Lielais prospekts 8, Ventspils' },
  { id:'lp-76', city:'Ventspils',   name:'LP Ventspils 2',                 address:'Kuldīgas iela 2, Ventspils' },
  { id:'lp-77', city:'Kuldīga',     name:'LP Kuldīga',                     address:'Baznīcas iela 2, Kuldīga' },
  { id:'lp-78', city:'Talsi',       name:'LP Talsi',                       address:'Kareivju iela 7, Talsi' },
  { id:'lp-79', city:'Tukums',      name:'LP Tukums',                      address:'Harmonijas iela 6, Tukums' },
  { id:'lp-80', city:'Saldus',      name:'LP Saldus',                      address:'Striķu iela 3, Saldus' },
  { id:'lp-81', city:'Kandava',     name:'LP Kandava',                     address:'Lielā iela 14, Kandava' },
]
