// 262 Omniva pakomāti Latvijā — statisks saraksts, atjaunots 2026
export const OMNIVA_PAKOMATI = [
  { id:'om-0',   city:'Aglona',       name:'Aglonas TOP pakomāts',                              address:'Somersētas iela 33, Aglona' },
  { id:'om-1',   city:'Aizkraukle',   name:'Aizkraukles TOP pakomāts',                          address:'Lāčplēša iela 7, Aizkraukle' },
  { id:'om-2',   city:'Aizkraukle',   name:'Aizkraukles T/C Iga pakomāts',                      address:'Gaismas iela 35, Aizkraukle' },
  { id:'om-3',   city:'Aizpute',      name:'Aizputes AIBE pakomāts',                            address:'Zvaigžņu iela 2B, Aizpute' },
  { id:'om-4',   city:'Aknīste',      name:'Aknīstes VESKO pakomāts',                           address:'Skolas iela 7, Aknīste' },
  { id:'om-5',   city:'Aloja',        name:'Alojas Mini Top pakomāts',                          address:'Rīgas iela 1b, Aloja' },
  { id:'om-6',   city:'Alūksne',      name:'Alūksnes Maxima X pakomāts',                        address:'Pils iela 9B, Alūksne' },
  { id:'om-7',   city:'Alūksne',      name:'Alūksnes Pils ielas TOP pakomāts',                  address:'Pils iela 38A, Alūksne' },
  { id:'om-8',   city:'Ape',          name:'Apes TOP pakomāts',                                 address:'Stacijas iela 4, Ape' },
  { id:'om-9',   city:'Auce',         name:'Auces TOP pakomāts',                                address:'Baznīcas iela 1, Auce' },
  { id:'om-10',  city:'Ādaži',        name:'Ādažu Mini RIMI pakomāts',                          address:'Gaujas iela 6, Ādaži' },
  { id:'om-11',  city:'Ādaži',        name:'Ādažu T/C Apelsīns pakomāts',                       address:'Rīgas gatve 5, Ādaži' },
  { id:'om-12',  city:'Ādaži',        name:'Ādažu Rīgas gatves ELVI pakomāts',                  address:'Rīgas gatve 51, Ādaži' },
  { id:'om-13',  city:'Baldone',      name:'Baldones MEGO pakomāts',                            address:'Rīgas iela 79, Baldone' },
  { id:'om-14',  city:'Balvi',        name:'Balvu Tautas ielas pakomāts',                       address:'Tautas iela 1, Balvi' },
  { id:'om-15',  city:'Balvi',        name:'Balvu TOP pakomāts',                                address:'Partizānu iela 8, Balvi' },
  { id:'om-16',  city:'Bauska',       name:'Bauskas Pionieru ielas RIMI pakomāts',              address:'Pionieru iela 2, Bauska' },
  { id:'om-17',  city:'Bauska',       name:'Bauskas Upmalas ielas TOP pakomāts',                address:'Upmalas iela 1, Bauska' },
  { id:'om-18',  city:'Bauska',       name:'Bauskas Mini RIMI pakomāts',                        address:'Zaļā iela 3, Bauska' },
  { id:'om-19',  city:'Brocēni',      name:'Brocēnu Citro pakomāts',                            address:'Lielcieceres iela 2A, Brocēni' },
  { id:'om-20',  city:'Cēsis',        name:'Cēsu Gaujas ielas Maxima pakomāts',                 address:'Gaujas iela 1/3, Cēsis' },
  { id:'om-21',  city:'Cēsis',        name:'Cēsu Gaujas ielas TOP pakomāts',                    address:'Gaujas iela 29, Cēsis' },
  { id:'om-22',  city:'Cēsis',        name:'Cēsu T/C SOLO pakomāts',                            address:'Jāņa Poruka iela 19, Cēsis' },
  { id:'om-23',  city:'Cēsis',        name:'Cēsu T/C Globuss pakomāts',                         address:'Raiņa iela 26/28, Cēsis' },
  { id:'om-24',  city:'Cēsis',        name:'Cēsu Valmieras ielas Maxima XX pakomāts',           address:'Valmieras iela 17A, Cēsis' },
  { id:'om-25',  city:'Cesvaine',     name:'Cesvaines TOP pakomāts',                            address:'Rīgas iela 2, Cesvaine' },
  { id:'om-26',  city:'Dagda',        name:'Dagdas TOP pakomāts',                               address:'Daugavpils iela 6, Dagda' },
  { id:'om-27',  city:'Daugavpils',   name:'Daugavpils LIDL pakomāts',                          address:'Balvu iela 1a, Daugavpils' },
  { id:'om-28',  city:'Daugavpils',   name:'Daugavpils Lats pakomāts',                          address:'Cialkovska iela 10A, Daugavpils' },
  { id:'om-29',  city:'Daugavpils',   name:'Daugavpils Gaismas ielas TOP pakomāts',             address:'Gaismas iela 12, Daugavpils' },
  { id:'om-30',  city:'Daugavpils',   name:'Daugavpils T/C Aveņu centrs pakomāts',              address:'Raipoles iela 11, Daugavpils' },
  { id:'om-31',  city:'Daugavpils',   name:'Daugavpils T/C Ditton pakomāts',                    address:'Cietokšņa iela 60, Daugavpils' },
  { id:'om-32',  city:'Daugavpils',   name:'Daugavpils T/C Solo pakomāts',                      address:'Rīgas iela 9, Daugavpils' },
  { id:'om-33',  city:'Daugavpils',   name:'Daugavpils Valkas ielas Mego pakomāts',             address:'Valkas iela 1, Daugavpils' },
  { id:'om-34',  city:'Daugavpils',   name:'Daugavpils Viestura ielas Mego pakomāts',           address:'Viestura iela 60, Daugavpils' },
  { id:'om-35',  city:'Daugavpils',   name:'Daugavpils 18. novembra ielas Lats pakomāts',       address:'18. novembra iela 398A, Daugavpils' },
  { id:'om-36',  city:'Daugavpils',   name:'Daugavpils 18. novembra ielas Rimi pakomāts',       address:'18. novembra iela 136, Daugavpils' },
  { id:'om-37',  city:'Dobele',       name:'Dobeles Brīvības ielas RIMI pakomāts',              address:'Brīvības iela 30, Dobele' },
  { id:'om-38',  city:'Dobele',       name:'Dobeles Krasta ielas TOP pakomāts',                 address:'Krasta iela 7, Dobele' },
  { id:'om-39',  city:'Dobele',       name:'Dobeles Muldavas ielas TOP pakomāts',               address:'Muldavas iela 3A, Dobele' },
  { id:'om-40',  city:'Dobele',       name:'Dobeles Zaļās ielas Maxima X pakomāts',             address:'Zaļā iela 19, Dobele' },
  { id:'om-41',  city:'Dundaga',      name:'Dundagas Citro pakomāts',                           address:'Talsu iela 1, Dundaga' },
  { id:'om-42',  city:'Ērgļi',        name:'Ērgļu TOP pakomāts',                                address:'Zaļā iela 1, Ērgļi' },
  { id:'om-43',  city:'Gulbene',      name:'Gulbenes Dzelzceļa ielas pakomāts',                 address:'Dzelzceļa iela 14, Gulbene' },
  { id:'om-44',  city:'Gulbene',      name:'Gulbenes Nākotnes ielas TOP pakomāts',              address:'Nākotnes iela 6, Gulbene' },
  { id:'om-45',  city:'Iecava',       name:'Iecavas Maxima X pakomāts',                         address:'Rīgas iela 27, Iecava' },
  { id:'om-46',  city:'Ikšķile',      name:'Ikšķiles Elvi pakomāts',                            address:'Daugavas prospekts 18A, Ikšķile' },
  { id:'om-47',  city:'Ikšķile',      name:'Ikšķiles Mini RIMI pakomāts',                       address:'Melioratoru iela 1A, Ikšķile' },
  { id:'om-48',  city:'Ilūkste',      name:'Ilūkstes TOP pakomāts',                             address:'Pilskalnes iela 2A, Ilūkste' },
  { id:'om-49',  city:'Inčukalns',    name:'Inčukalna Aibe pakomāts',                           address:'Atmodas iela 6, Inčukalns' },
  { id:'om-50',  city:'Jelgava',      name:'Jelgavas Birzes ielas LATS pakomāts',               address:'Birzes iela 21, Jelgava' },
  { id:'om-51',  city:'Jelgava',      name:'Jelgavas Lielās ielas ELVI pakomāts',               address:'Lielā iela 49, Jelgava' },
  { id:'om-52',  city:'Jelgava',      name:'Jelgavas Pilsētas Pasāžas pakomāts',                address:'Driksas iela 4, Jelgava' },
  { id:'om-53',  city:'Jelgava',      name:'Jelgavas Rūpniecības ielas ELVI pakomāts',          address:'Rūpniecības iela 77a, Jelgava' },
  { id:'om-54',  city:'Jelgava',      name:'Jelgavas Satiksmes ielas RIMI pakomāts',            address:'Satiksmes iela 35, Jelgava' },
  { id:'om-55',  city:'Jelgava',      name:'Jelgavas Tērvetes ielas TOP pakomāts',              address:'Tērvetes iela 97, Jelgava' },
  { id:'om-56',  city:'Jelgava',      name:'Jelgavas T/C RAF Centrs pakomāts',                  address:'Rīgas iela 48, Jelgava' },
  { id:'om-57',  city:'Jelgava',      name:'Jelgavas T/C Valdeka pakomāts',                     address:'Rīgas iela 11A, Jelgava' },
  { id:'om-58',  city:'Jelgava',      name:'Jelgavas T/C Vivo centrs pakomāts',                 address:'Katoļu iela 18, Jelgava' },
  { id:'om-59',  city:'Jēkabpils',    name:'Jēkabpils Nameja ielas TOP pakomāts',               address:'Nameja iela 12, Jēkabpils' },
  { id:'om-60',  city:'Jēkabpils',    name:'Jēkabpils Vienības ielas Mego pakomāts',            address:'Vienības iela 1A, Jēkabpils' },
  { id:'om-61',  city:'Jēkabpils',    name:'Jēkabpils Rīgas ielas Mini RIMI pakomāts',          address:'Rīgas iela 120, Jēkabpils' },
  { id:'om-62',  city:'Jēkabpils',    name:'Jēkabpils T/C Sēlija pakomāts',                    address:'Vienības iela 7, Jēkabpils' },
  { id:'om-63',  city:'Jēkabpils',    name:'Jēkabpils T/C Sprīdītis pakomāts',                 address:'Celtnieku iela 1, Jēkabpils' },
  { id:'om-64',  city:'Jūrmala',      name:'Jūrmalas Dubultu TOP pakomāts',                     address:'Strēlnieku prospekts 1, Jūrmala' },
  { id:'om-65',  city:'Jūrmala',      name:'Jūrmalas Kauguru RIMI pakomāts',                    address:'Talsu šoseja 29, Jūrmala' },
  { id:'om-66',  city:'Jūrmala',      name:'Jūrmalas Lielupes RIMI pakomāts',                   address:'Viestura iela 22, Jūrmala' },
  { id:'om-67',  city:'Jūrmala',      name:'Jūrmalas Raiņa ielas RIMI pakomāts',                address:'Raiņa iela 74, Jūrmala' },
  { id:'om-68',  city:'Jūrmala',      name:'Jūrmalas Slokas T/C Liedags pakomāts',              address:'Ventspils šoseja 32, Jūrmala' },
  { id:'om-69',  city:'Kandava',      name:'Kandavas Citro pakomāts',                           address:'Lielā iela 1, Kandava' },
  { id:'om-70',  city:'Kārsava',      name:'Kārsavas Citro pakomāts',                           address:'Sporta iela 6, Kārsava' },
  { id:'om-71',  city:'Koknese',      name:'Kokneses Lats pakomāts',                            address:'Hanzas iela 1, Koknese' },
  { id:'om-72',  city:'Krāslava',     name:'Krāslavas Maxima X pakomāts',                       address:'Rīgas iela 28, Krāslava' },
  { id:'om-73',  city:'Kuldīga',      name:'Kuldīgas Sūru ielas RIMI pakomāts',                 address:'Sūru iela 2, Kuldīga' },
  { id:'om-74',  city:'Kuldīga',      name:'Kuldīgas Citro pakomāts',                           address:'Stendes iela 23A, Kuldīga' },
  { id:'om-75',  city:'Kuldīga',      name:'Kuldīgas Gravas ielas ELVI pakomāts',               address:'Gravas iela 1, Kuldīga' },
  { id:'om-76',  city:'Ķekava',       name:'Ķekavas T/C Dālderi pakomāts',                      address:'Nākotnes iela 1, Ķekava' },
  { id:'om-77',  city:'Ķekava',       name:'Ķekavas T/C Liiba pakomāts',                        address:'Rīgas iela 22A, Ķekava' },
  { id:'om-78',  city:'Ķekava',       name:'Ķekavas Rīgas ielas RIMI pakomāts',                 address:'Rīgas iela 22, Ķekava' },
  { id:'om-79',  city:'Lielvārde',    name:'Lielvārdes TOP pakomāts',                           address:'Lāčplēša iela 16, Lielvārde' },
  { id:'om-80',  city:'Liepāja',      name:'Liepājas Ganību ielas ELVI pakomāts',               address:'Ganību iela 69/71, Liepāja' },
  { id:'om-81',  city:'Liepāja',      name:'Liepājas Ganību ielas JYSK pakomāts',               address:'Ganību iela 187, Liepāja' },
  { id:'om-82',  city:'Liepāja',      name:'Liepājas O. Kalpaka ielas pakomāts',                address:'Oskara Kalpaka iela 74, Liepāja' },
  { id:'om-83',  city:'Liepāja',      name:'Liepājas Kuršu laukuma pakomāts',                   address:'Kuršu laukums 10, Liepāja' },
  { id:'om-84',  city:'Liepāja',      name:'Liepājas P. Brieža ielas TOP pakomāts',             address:'Pulkveža Brieža iela 14, Liepāja' },
  { id:'om-85',  city:'Liepāja',      name:'Liepājas Rožu laukuma pakomāts',                    address:'Lielā iela 13, Liepāja' },
  { id:'om-86',  city:'Liepāja',      name:'Liepājas T/C Baata pakomāts',                       address:'Klaipēdas iela 104C, Liepāja' },
  { id:'om-87',  city:'Liepāja',      name:'Liepājas T/C Rietumu centrs pakomāts',              address:'Jaunā Ostmala 3/5, Liepāja' },
  { id:'om-88',  city:'Liepāja',      name:'Liepājas Sila ielas TOP pakomāts',                  address:'Sila iela 3, Liepāja' },
  { id:'om-89',  city:'Liepāja',      name:'Liepājas Ziemeļu ielas RIMI pakomāts',              address:'Ziemeļu iela 13, Liepāja' },
  { id:'om-90',  city:'Limbaži',      name:'Limbažu Pasta ielas ELVI pakomāts',                 address:'Pasta iela 1, Limbaži' },
  { id:'om-91',  city:'Limbaži',      name:'Limbažu RIMI pakomāts',                             address:'Cēsu iela 23, Limbaži' },
  { id:'om-92',  city:'Līvāni',       name:'Līvānu Rimi pakomāts',                              address:'Rīgas iela 89, Līvāni' },
  { id:'om-93',  city:'Ludza',        name:'Ludzas Stacijas ielas pakomāts',                    address:'Stacijas iela 30, Ludza' },
  { id:'om-94',  city:'Madona',       name:'Madonas MINI RIMI pakomāts',                        address:'Rūpniecības iela 47, Madona' },
  { id:'om-95',  city:'Madona',       name:'Madonas Raiņa ielas pakomāts',                      address:'Raiņa iela 34, Madona' },
  { id:'om-96',  city:'Madona',       name:'Madonas Saules ielas pakomāts',                     address:'Saules iela 4, Madona' },
  { id:'om-97',  city:'Malta',        name:'Maltas Lats pakomāts',                              address:'1. maija iela 44, Malta' },
  { id:'om-98',  city:'Mārupe',       name:'Mārupes Daugavas ielas ELVI pakomāts',              address:'Daugavas iela 36, Mārupe' },
  { id:'om-99',  city:'Mārupe',       name:'Mārupes Dzirnieku ielas pakomāts',                  address:'Dzirnieku iela 24, Mārupe' },
  { id:'om-100', city:'Mārupe',       name:'Mārupes Lielās ielas ELVI pakomāts',                address:'Lielā iela 26, Mārupe' },
  { id:'om-101', city:'Mārupe',       name:'Mārupes RIMI pakomāts',                             address:'Daugavas iela 31, Mārupe' },
  { id:'om-102', city:'Mazsalaca',    name:'Mazsalacas pakomāts',                               address:'Parka iela 1, Mazsalaca' },
  { id:'om-103', city:'Naukšēni',     name:'Naukšēnu Lats pakomāts',                            address:'Naukšēni' },
  { id:'om-104', city:'Nereta',       name:'Neretas TOP pakomāts',                              address:'Raiņa iela 6, Nereta' },
  { id:'om-105', city:'Ogre',         name:'Ogres Brīvības ielas pakomāts',                     address:'Brīvības iela 19, Ogre' },
  { id:'om-106', city:'Ogre',         name:'Ogres Kartona fabrikas pakomāts',                   address:'Brīvības iela 116, Ogre' },
  { id:'om-107', city:'Ogre',         name:'Ogres Mālkalnes prospekta pakomāts',                address:'Mālkalnes prospekts 3, Ogre' },
  { id:'om-108', city:'Ogre',         name:'Ogres Rīgas ielas RIMI pakomāts',                   address:'Rīgas iela 33, Ogre' },
  { id:'om-109', city:'Ogre',         name:'Ogres T/C Dauga pakomāts',                          address:'Rīgas iela 23, Ogre' },
  { id:'om-110', city:'Ogre',         name:'Ogres T/C Ogres prestižs pakomāts',                 address:'Mednieku iela 21/23, Ogre' },
  { id:'om-111', city:'Olaine',       name:'Olaines Stacijas ielas RIMI pakomāts',              address:'Stacijas iela 8, Olaine' },
  { id:'om-112', city:'Olaine',       name:'Olaines T/C Prasme pakomāts',                       address:'Zemgales iela 24, Olaine' },
  { id:'om-113', city:'Ozolnieki',    name:'Ozolnieku ELVI pakomāts',                           address:'Rīgas iela 42, Ozolnieki' },
  { id:'om-114', city:'Pļaviņas',     name:'Pļaviņu TOP pakomāts',                              address:'Daugavas iela 85, Pļaviņas' },
  { id:'om-115', city:'Preiļi',       name:'Preiļu Brīvības ielas TOP pakomāts',                address:'Brīvības iela 4, Preiļi' },
  { id:'om-116', city:'Preiļi',       name:'Preiļu Rīgas ielas MEGO pakomāts',                  address:'Rīgas iela 4D, Preiļi' },
  { id:'om-117', city:'Priekule',     name:'Priekules TOP pakomāts',                            address:'Galvenā iela 1, Priekule' },
  { id:'om-118', city:'Priekuļi',     name:'Priekuļu Aibe pakomāts',                            address:'Cēsu prospekts 44, Priekuļi' },
  { id:'om-119', city:'Rauna',        name:'Raunas TOP pakomāts',                               address:'Cēsu iela 2A, Rauna' },
  { id:'om-120', city:'Rēzekne',      name:'Rēzeknes Dārzu ielas pakomāts',                     address:'Dārzu iela 63, Rēzekne' },
  { id:'om-121', city:'Rēzekne',      name:'Rēzeknes ELFI pakomāts',                            address:'Dārzu iela 14a, Rēzekne' },
  { id:'om-122', city:'Rēzekne',      name:'Rēzeknes Galdnieku ielas RIMI pakomāts',            address:'Galdnieku iela 8, Rēzekne' },
  { id:'om-123', city:'Rēzekne',      name:'Rēzeknes Kr. Valdemāra ielas Mego pakomāts',        address:'Kr. Valdemāra iela 16a, Rēzekne' },
  { id:'om-124', city:'Rēzekne',      name:'Rēzeknes Atbrīvošanas alejas Maxima XX pakomāts',   address:'Atbrīvošanas aleja 141, Rēzekne' },
  { id:'om-125', city:'Rēzekne',      name:'Rēzeknes Stacijas ielas pakomāts',                  address:'Stacijas iela 20A, Rēzekne' },
  { id:'om-126', city:'Roja',         name:'Rojas Maxima X pakomāts',                           address:'Selgas iela 2, Roja' },
  { id:'om-127', city:'Ropaži',       name:'Ropažu Lats pakomāts',                              address:'Rīgas iela 12, Ropaži' },
  { id:'om-128', city:'Rūjiena',      name:'Rūjienas TOP pakomāts',                             address:'Brīvības iela 8, Rūjiena' },
  { id:'om-129', city:'Salacgrīva',   name:'Salacgrīvas Maxima X pakomāts',                     address:'Vidzemes iela 3a, Salacgrīva' },
  { id:'om-130', city:'Salaspils',    name:'Salaspils LIDL pakomāts',                           address:'Skolas iela 4A, Salaspils' },
  { id:'om-131', city:'Salaspils',    name:'Salaspils AIBE pakomāts',                           address:'Miera iela 24, Salaspils' },
  { id:'om-132', city:'Salaspils',    name:'Salaspils Rīgas ielas TOP pakomāts',                address:'Rīgas iela 48, Salaspils' },
  { id:'om-133', city:'Salaspils',    name:'Salaspils Rīgas ielas ELVI pakomāts',               address:'Rīgas iela 24, Salaspils' },
  { id:'om-134', city:'Salaspils',    name:'Salaspils Skolas ielas RIMI pakomāts',              address:'Skolas iela 4, Salaspils' },
  { id:'om-135', city:'Saldus',       name:'Saldus Brīvības ielas Maxima XX pakomāts',          address:'Brīvības iela 30, Saldus' },
  { id:'om-136', city:'Saldus',       name:'Saldus Lielās ielas Lats pakomāts',                 address:'Lielā iela 73, Saldus' },
  { id:'om-137', city:'Saldus',       name:'Saldus Striķu ielas Maxima X pakomāts',             address:'Striķu iela 10C, Saldus' },
  { id:'om-138', city:'Saldus',       name:'Saldus AIBE pakomāts',                              address:'Kalna iela 20, Saldus' },
  { id:'om-139', city:'Saulkrasti',   name:'Saulkrastu ELVI pakomāts',                          address:'Ainažu iela 28A, Saulkrasti' },
  { id:'om-140', city:'Saulkrasti',   name:'Saulkrastu TOP pakomāts',                           address:'Rīgas iela 51, Saulkrasti' },
  { id:'om-141', city:'Sigulda',      name:'Siguldas T/C Gāles Nams pakomāts',                  address:'Gāles iela 23A, Sigulda' },
  { id:'om-142', city:'Sigulda',      name:'Siguldas Leona Paegles ielas Maxima pakomāts',      address:'Leona Paegles iela 3, Sigulda' },
  { id:'om-143', city:'Sigulda',      name:'Siguldas T/C Šokolāde pakomāts',                    address:'Strēlnieku iela 2, Sigulda' },
  { id:'om-144', city:'Sigulda',      name:'Siguldas Vidus ielas ELVI pakomāts',                address:'Vidus iela 1, Sigulda' },
  { id:'om-145', city:'Smiltene',     name:'Smiltenes Daugavas ielas TOP pakomāts',             address:'Daugavas iela 1B, Smiltene' },
  { id:'om-146', city:'Smiltene',     name:'Smiltenes Rīgas ielas TOP pakomāts',                address:'Rīgas iela 5, Smiltene' },
  { id:'om-147', city:'Smiltene',     name:'Smiltenes T/C Centrs pakomāts',                     address:'Baznīcas laukums 2, Smiltene' },
  { id:'om-148', city:'Strenči',      name:'Strenču TOP pakomāts',                              address:'Valkas iela 2, Strenči' },
  { id:'om-149', city:'Suntaži',      name:'Suntažu AIBE pakomāts',                             address:'Suntaži' },
  { id:'om-150', city:'Talsi',        name:'Talsu Dundagas ielas Citro pakomāts',               address:'Dundagas iela 21, Talsi' },
  { id:'om-151', city:'Talsi',        name:'Talsu Dundagas ielas RIMI pakomāts',                address:'Dundagas iela 18, Talsi' },
  { id:'om-152', city:'Talsi',        name:'Talsu Rīgas ielas Maxima XX pakomāts',              address:'Rīgas iela 8, Talsi' },
  { id:'om-153', city:'Talsi',        name:'Talsu T/C Talsu Centrs pakomāts',                   address:'Lielā iela 2, Talsi' },
  { id:'om-154', city:'Tukums',       name:'Tukuma Alīnes ielas TOP pakomāts',                  address:'Alīnes iela 1A, Tukums' },
  { id:'om-155', city:'Tukums',       name:'Tukuma Kurzemes ielas Mego pakomāts',               address:'Kurzemes iela 2A, Tukums' },
  { id:'om-156', city:'Tukums',       name:'Tukuma Kurzemes ielas Maxima XX pakomāts',          address:'Kurzemes iela 36, Tukums' },
  { id:'om-157', city:'Tukums',       name:'Tukuma Pasta ielas RIMI pakomāts',                  address:'Pasta iela 14, Tukums' },
  { id:'om-158', city:'Tukums',       name:'Tukuma LIDL pakomāts',                              address:'Raudas iela 17a, Tukums' },
  { id:'om-159', city:'Tukums',       name:'Tukuma T/C Aplis pakomāts',                         address:'Eksporta iela 6, Tukums' },
  { id:'om-160', city:'Valka',        name:'Valkas Raiņa ielas Maxima X pakomāts',              address:'Raiņa iela 7, Valka' },
  { id:'om-161', city:'Valka',        name:'Valkas T/C Walk pakomāts',                          address:'Ausekļa iela 54, Valka' },
  { id:'om-162', city:'Valmiera',     name:'Valmieras Fabrikas ielas RIMI pakomāts',            address:'Fabrikas iela 2, Valmiera' },
  { id:'om-163', city:'Valmiera',     name:'Valmieras Nākotnes ielas Maxima X pakomāts',        address:'Nākotnes iela 2A, Valmiera' },
  { id:'om-164', city:'Valmiera',     name:'Valmieras Miera ielas TOP pakomāts',                address:'Miera iela 5, Valmiera' },
  { id:'om-165', city:'Valmiera',     name:'Valmieras Rīgas ielas TOP pakomāts',                address:'Rīgas iela 64, Valmiera' },
  { id:'om-166', city:'Valmiera',     name:'Valmieras Rubenes ielas RIMI pakomāts',             address:'Rubenes iela 51, Valmiera' },
  { id:'om-167', city:'Valmiera',     name:'Valmieras T/C Valleta pakomāts',                    address:'Rīgas iela 4, Valmiera' },
  { id:'om-168', city:'Valmiera',     name:'Valmieras Stacijas ielas pakomāts',                 address:'Stacijas iela 33, Valmiera' },
  { id:'om-169', city:'Vangaži',      name:'Vangažu Aibes pakomāts',                            address:'Gaujas iela 19A, Vangaži' },
  { id:'om-170', city:'Varakļāni',    name:'Varakļānu TOP pakomāts',                            address:'Pils iela 7D, Varakļāni' },
  { id:'om-171', city:'Vecpiebalga',  name:'Vecpiebalgas TOP pakomāts',                         address:'Alauksta iela 2, Vecpiebalga' },
  { id:'om-172', city:'Vecumnieki',   name:'Vecumnieku Lats pakomāts',                          address:'Rīgas iela 24B, Vecumnieki' },
  { id:'om-173', city:'Ventspils',    name:'Ventspils Celtnieku ielas ELVI pakomāts',           address:'Celtnieku iela 3, Ventspils' },
  { id:'om-174', city:'Ventspils',    name:'Ventspils Ganību ielas Mego pakomāts',              address:'Ganību iela 22/24, Ventspils' },
  { id:'om-175', city:'Ventspils',    name:'Ventspils Mini RIMI pakomāts',                      address:'Tārgales iela 62, Ventspils' },
  { id:'om-176', city:'Ventspils',    name:'Ventspils Poruka ielas RIMI pakomāts',              address:'J. Poruka iela 5, Ventspils' },
  { id:'om-177', city:'Ventspils',    name:'Ventspils Inženieru ielas MEGO pakomāts',           address:'Inženieru iela 65, Ventspils' },
  { id:'om-178', city:'Ventspils',    name:'Ventspils Talsu ielas Citro pakomāts',              address:'Talsu iela 6, Ventspils' },
  { id:'om-179', city:'Ventspils',    name:'Ventspils T/C Tobago pakomāts',                     address:'Lielais prospekts 3/5, Ventspils' },
  { id:'om-180', city:'Viesīte',      name:'Viesītes TOP pakomāts',                             address:'Raiņa iela 23, Viesīte' },
  { id:'om-181', city:'Viļaka',       name:'Viļakas Balvu ielas pakomāts',                      address:'Balvu iela 5, Viļaka' },
  { id:'om-182', city:'Viļāni',       name:'Viļānu Brīvības ielas pakomāts',                    address:'Brīvības iela 13, Viļāni' },
  { id:'om-183', city:'Zilupe',       name:'Zilupes TOP pakomāts',                              address:'Brīvības iela 34, Zilupe' },
  // ── Rīga ──
  { id:'om-184', city:'Rīga', name:'Rīgas Autoostas pakomāts',                                  address:'Prāgas iela 1, Rīga' },
  { id:'om-185', city:'Rīga', name:'Rīgas Āgenskalna Maxima X pakomāts',                        address:'Pilsoņu iela 1k-1, Rīga' },
  { id:'om-186', city:'Rīga', name:'Rīgas Āgenskalna RIMI pakomāts',                            address:'Mārupes iela 10A, Rīga' },
  { id:'om-187', city:'Rīga', name:'Rīgas Barons Kvartāls pakomāts',                            address:'Cēsu iela 31, Rīga' },
  { id:'om-188', city:'Rīga', name:'Rīgas Biķernieku ielas MEGO pakomāts',                      address:'Biķernieku iela 16A, Rīga' },
  { id:'om-189', city:'Rīga', name:'Rīgas Biķernieku ielas RIMI pakomāts',                      address:'Biķernieku iela 160/6, Rīga' },
  { id:'om-190', city:'Rīga', name:'Rīgas Bolderājas Mego pakomāts',                            address:'Gobas iela 13, Rīga' },
  { id:'om-191', city:'Rīga', name:'Rīgas Brīvības ielas 35 pakomāts',                          address:'Brīvības iela 35, Rīga' },
  { id:'om-192', city:'Rīga', name:'Rīgas Brīvības ielas LIDL pakomāts',                        address:'Brīvības iela 254, Rīga' },
  { id:'om-193', city:'Rīga', name:'Rīgas Brīvības gatves RIMI pakomāts',                       address:'Brīvības iela 404, Rīga' },
  { id:'om-194', city:'Rīga', name:'Rīgas Buļļu ielas Aibe pakomāts',                           address:'Buļļu iela 35, Rīga' },
  { id:'om-195', city:'Rīga', name:'Rīgas Dammes tirgus pakomāts',                              address:'Dammes iela 36A, Rīga' },
  { id:'om-196', city:'Rīga', name:'Rīgas Daugavgrīvas ielas TOP pakomāts',                     address:'Daugavgrīvas iela 72, Rīga' },
  { id:'om-197', city:'Rīga', name:'Rīgas Deglava ielas Maxima XXX pakomāts',                   address:'Augusta Deglava iela 67, Rīga' },
  { id:'om-198', city:'Rīga', name:'Rīgas Dzelzavas ielas LIDL pakomāts',                       address:'Dzelzavas iela 75, Rīga' },
  { id:'om-199', city:'Rīga', name:'Rīgas Dzelzavas ielas RIMI pakomāts',                       address:'Dzelzavas iela 78, Rīga' },
  { id:'om-200', city:'Rīga', name:'Rīgas Gramzdas RIMI pakomāts',                              address:'Imantas 15. līnija 7, Rīga' },
  { id:'om-201', city:'Rīga', name:'Rīgas Graudu ielas Mego pakomāts',                          address:'Graudu iela 10, Rīga' },
  { id:'om-202', city:'Rīga', name:'Rīgas Juglas ielas Mini RIMI pakomāts',                     address:'Juglas iela 25, Rīga' },
  { id:'om-203', city:'Rīga', name:'Rīgas Jūrmalas gatves RIMI pakomāts',                       address:'Anniņmuižas bulvāris 90, Rīga' },
  { id:'om-204', city:'Rīga', name:'Rīgas Kalnciema ielas LIDL pakomāts',                       address:'Kalnciema iela 38, Rīga' },
  { id:'om-205', city:'Rīga', name:'Rīgas Kalnciema ielas RIMI pakomāts',                       address:'Kalnciema iela 41, Rīga' },
  { id:'om-206', city:'Rīga', name:'Rīgas Kalpaka bulvāra pakomāts',                            address:'Kalpaka bulvāris 14A, Rīga' },
  { id:'om-207', city:'Rīga', name:'Rīgas Kleistu ielas Mego pakomāts',                         address:'Kleistu iela 9, Rīga' },
  { id:'om-208', city:'Rīga', name:'Rīgas Kr.Valdemāra ielas RIMI pakomāts',                    address:'Krišjāņa Valdemāra iela 112, Rīga' },
  { id:'om-209', city:'Rīga', name:'Rīgas Kurzemes prospekta Mego pakomāts',                    address:'Kurzemes prospekts 132, Rīga' },
  { id:'om-210', city:'Rīga', name:'Rīgas Latgales ielas RIMI pakomāts',                        address:'Latgales iela 256B, Rīga' },
  { id:'om-211', city:'Rīga', name:'Rīgas Latgales ielas LIDL pakomāts',                        address:'Latgales iela 414, Rīga' },
  { id:'om-212', city:'Rīga', name:'Rīgas Lubānas ielas LIDL pakomāts',                         address:'Lubānas iela 113a, Rīga' },
  { id:'om-213', city:'Rīga', name:'Rīgas Miera ielas pakomāts',                                address:'Miera iela 2, Rīga' },
  { id:'om-214', city:'Rīga', name:'Rīgas Mīlgravja ielas RIMI pakomāts',                       address:'Mīlgravja iela 14, Rīga' },
  { id:'om-215', city:'Rīga', name:'Rīgas Jaunciema gatves Maxima X pakomāts',                  address:'Jaunciema gatve 174, Rīga' },
  { id:'om-216', city:'Rīga', name:'Rīgas Ķīšezera ielas RIMI pakomāts',                        address:'Ķīšezera iela 6, Rīga' },
  { id:'om-217', city:'Rīga', name:'Rīgas Lāčplēša ielas pakomāts',                             address:'Lāčplēša iela 57, Rīga' },
  { id:'om-218', city:'Rīga', name:'Rīgas Leļļu teātra pakomāts',                               address:'Elizabetes iela 81, Rīga' },
  { id:'om-219', city:'Rīga', name:'Rīgas Lidoņu ielas Mego pakomāts',                          address:'Lidoņu iela 27 k-1, Rīga' },
  { id:'om-220', city:'Rīga', name:'Rīgas Liepājas ielas Maxima X pakomāts',                    address:'Liepājas iela 76A, Rīga' },
  { id:'om-221', city:'Rīga', name:'Rīgas S. Eizenšteina ielas LIDL pakomāts',                  address:'Sergeja Eizenšteina iela 81, Rīga' },
  { id:'om-222', city:'Rīga', name:'Rīgas Mūkusalas Maxima XX pakomāts',                        address:'Mūkusalas iela 73, Rīga' },
  { id:'om-223', city:'Rīga', name:'Rīgas Nīcgales ielas T/C GREEN pakomāts',                   address:'Nīcgales iela 53, Rīga' },
  { id:'om-224', city:'Rīga', name:'Rīgas P.Brieža ielas RIMI pakomāts',                        address:'Pulkveža Brieža iela 33, Rīga' },
  { id:'om-225', city:'Rīga', name:'Rīgas Pētersalas ielas Maxima X pakomāts',                  address:'Pētersalas iela 18A, Rīga' },
  { id:'om-226', city:'Rīga', name:'Rīgas Prūšu ielas LIDL pakomāts',                           address:'Prūšu iela 1, Rīga' },
  { id:'om-227', city:'Rīga', name:'Rīgas Prūšu ielas Mego pakomāts',                           address:'Prūšu iela 2, Rīga' },
  { id:'om-228', city:'Rīga', name:'Rīgas Rītupes ielas Maxima X pakomāts',                     address:'Rītupes iela 2, Rīga' },
  { id:'om-229', city:'Rīga', name:'Rīgas Saharova ielas Maxima XXX pakomāts',                  address:'Saharova iela 20a, Rīga' },
  { id:'om-230', city:'Rīga', name:'Rīgas Saharova ielas Mego pakomāts',                        address:'Saharova iela 14, Rīga' },
  { id:'om-231', city:'Rīga', name:'Rīgas Saharova ielas RIMI pakomāts',                        address:'Saharova iela 23, Rīga' },
  { id:'om-232', city:'Rīga', name:'Rīgas Sporta Pils dārzu pakomāts',                          address:'Lielgabalu iela 4, Rīga' },
  { id:'om-233', city:'Rīga', name:'Rīgas Stabu ielas pakomāts',                                address:'Stabu iela 24, Rīga' },
  { id:'om-234', city:'Rīga', name:'Rīgas Stirnu ielas Rimi pakomāts',                          address:'Stirnu iela 26, Rīga' },
  { id:'om-235', city:'Rīga', name:'Rīgas T/C Akropole Riga pakomāts',                          address:'Latgales iela 257, Rīga' },
  { id:'om-236', city:'Rīga', name:'Rīgas T/C Aleja pakomāts',                                  address:'Vienības gatve 194A, Rīga' },
  { id:'om-237', city:'Rīga', name:'Rīgas T/C AKROPOLE Alfa pakomāts',                          address:'Brīvības iela 372, Rīga' },
  { id:'om-238', city:'Rīga', name:'Rīgas T/C Damme pakomāts',                                  address:'Kurzemes prospekts 1a, Rīga' },
  { id:'om-239', city:'Rīga', name:'Rīgas T/C Dole pakomāts',                                   address:'Latgales iela 357, Rīga' },
  { id:'om-240', city:'Rīga', name:'Rīgas T/C DOMINA pakomāts',                                 address:'Ieriķu iela 3, Rīga' },
  { id:'om-241', city:'Rīga', name:'Rīgas T/C Gaiļezers pakomāts',                              address:'Gaiļezera iela 8, Rīga' },
  { id:'om-242', city:'Rīga', name:'Rīgas T/C Galleria Riga pakomāts',                          address:'Dzirnavu iela 67, Rīga' },
  { id:'om-243', city:'Rīga', name:'Rīgas T/C IXO pakomāts',                                    address:'Anniņmuižas iela 17, Rīga' },
  { id:'om-244', city:'Rīga', name:'Rīgas T/C Juglas Centrs pakomāts',                          address:'Juglas iela 2, Rīga' },
  { id:'om-245', city:'Rīga', name:'Rīgas T/C Minska pakomāts',                                 address:'Nīcgales iela 2, Rīga' },
  { id:'om-246', city:'Rīga', name:'Rīgas T/C Mols pakomāts',                                   address:'Krasta iela 46, Rīga' },
  { id:'om-247', city:'Rīga', name:'Rīgas T/C Olimpia pakomāts',                                address:'Āzenes iela 5, Rīga' },
  { id:'om-248', city:'Rīga', name:'Rīgas T/C Origo pakomāts',                                  address:'Stacijas laukums 2, Rīga' },
  { id:'om-249', city:'Rīga', name:'Rīgas T/C Riga Plaza pakomāts',                             address:'Mūkusalas iela 71, Rīga' },
  { id:'om-250', city:'Rīga', name:'Rīgas T/C Spice pakomāts',                                  address:'Lielirbes iela 29, Rīga' },
  { id:'om-251', city:'Rīga', name:'Rīgas T/C Venta pakomāts',                                  address:'Zolitūdes iela 34, Rīga' },
  { id:'om-252', city:'Rīga', name:'Rīgas Tēriņu ielas pakomāts',                               address:'Tēriņu iela 55, Rīga' },
  { id:'om-253', city:'Rīga', name:'Rīgas Tilta ielas RIMI pakomāts',                           address:'Tilta iela 32, Rīga' },
  { id:'om-254', city:'Rīga', name:'Rīgas Vaidavas ielas RIMI pakomāts',                        address:'Vaidavas iela 9B, Rīga' },
  { id:'om-255', city:'Rīga', name:'Rīgas Valdeķu ielas Maxima pakomāts',                       address:'Valdeķu iela 10, Rīga' },
  { id:'om-256', city:'Rīga', name:'Rīgas Valdeķu ielas LIDL pakomāts',                         address:'Valdeķu iela 39a, Rīga' },
  { id:'om-257', city:'Rīga', name:'Rīgas Valmieras ielas pakomāts',                            address:'Valmieras iela 2, Rīga' },
  { id:'om-258', city:'Rīga', name:'Rīgas Vecmīlgrāvja Maxima pakomāts',                        address:'Augusta Dombrovska iela 74, Rīga' },
  { id:'om-259', city:'Rīga', name:'Rīgas Zalves ielas TOP pakomāts',                           address:'Zalves iela 46A, Rīga' },
  { id:'om-260', city:'Rīga', name:'Rīgas Anniņmuižas bulvāra RIMI pakomāts',                   address:'Anniņmuižas bulvāris 40A, Rīga' },
  { id:'om-261', city:'Rīga', name:'Rīgas Teika Plaza pakomāts',                                address:'Brīvības gatve 201, Rīga' },
]
